<?php

namespace ContainerIZF4qrH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ttk9YRPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ttk9YRP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\BddController::index' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\BddController::index()', 'getBddControllerindexService', true],
            'App\\Controller\\BddController::show_article' => ['privates', '.service_locator.RGWK.nN.App\\Controller\\BddController::show_article()', 'getBddControllershowArticleService', true],
            'App\\Controller\\BddController::modifier_article' => ['privates', '.service_locator.V05Esnz.App\\Controller\\BddController::modifier_article()', 'getBddControllermodifierArticleService', true],
            'App\\Controller\\BddController::supprimer_article' => ['privates', '.service_locator.V05Esnz.App\\Controller\\BddController::supprimer_article()', 'getBddControllersupprimerArticleService', true],
            'App\\Controller\\BddController::create_restaurant' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\BddController::create_restaurant()', 'getBddControllercreateRestaurantService', true],
            'App\\Controller\\BddController::modifier_restaurant' => ['privates', '.service_locator.vdrtoh..App\\Controller\\BddController::modifier_restaurant()', 'getBddControllermodifierRestaurantService', true],
            'App\\Controller\\BddController::supprimer_restaurant' => ['privates', '.service_locator.vdrtoh..App\\Controller\\BddController::supprimer_restaurant()', 'getBddControllersupprimerRestaurantService', true],
            'App\\Controller\\BddController::show_restaurant' => ['privates', '.service_locator.JOUdUxO.App\\Controller\\BddController::show_restaurant()', 'getBddControllershowRestaurantService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\BddController:index' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\BddController::index()', 'getBddControllerindexService', true],
            'App\\Controller\\BddController:show_article' => ['privates', '.service_locator.RGWK.nN.App\\Controller\\BddController::show_article()', 'getBddControllershowArticleService', true],
            'App\\Controller\\BddController:modifier_article' => ['privates', '.service_locator.V05Esnz.App\\Controller\\BddController::modifier_article()', 'getBddControllermodifierArticleService', true],
            'App\\Controller\\BddController:supprimer_article' => ['privates', '.service_locator.V05Esnz.App\\Controller\\BddController::supprimer_article()', 'getBddControllersupprimerArticleService', true],
            'App\\Controller\\BddController:create_restaurant' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\BddController::create_restaurant()', 'getBddControllercreateRestaurantService', true],
            'App\\Controller\\BddController:modifier_restaurant' => ['privates', '.service_locator.vdrtoh..App\\Controller\\BddController::modifier_restaurant()', 'getBddControllermodifierRestaurantService', true],
            'App\\Controller\\BddController:supprimer_restaurant' => ['privates', '.service_locator.vdrtoh..App\\Controller\\BddController::supprimer_restaurant()', 'getBddControllersupprimerRestaurantService', true],
            'App\\Controller\\BddController:show_restaurant' => ['privates', '.service_locator.JOUdUxO.App\\Controller\\BddController::show_restaurant()', 'getBddControllershowRestaurantService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\BddController::index' => '?',
            'App\\Controller\\BddController::show_article' => '?',
            'App\\Controller\\BddController::modifier_article' => '?',
            'App\\Controller\\BddController::supprimer_article' => '?',
            'App\\Controller\\BddController::create_restaurant' => '?',
            'App\\Controller\\BddController::modifier_restaurant' => '?',
            'App\\Controller\\BddController::supprimer_restaurant' => '?',
            'App\\Controller\\BddController::show_restaurant' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\BddController:index' => '?',
            'App\\Controller\\BddController:show_article' => '?',
            'App\\Controller\\BddController:modifier_article' => '?',
            'App\\Controller\\BddController:supprimer_article' => '?',
            'App\\Controller\\BddController:create_restaurant' => '?',
            'App\\Controller\\BddController:modifier_restaurant' => '?',
            'App\\Controller\\BddController:supprimer_restaurant' => '?',
            'App\\Controller\\BddController:show_restaurant' => '?',
        ]);

        if (isset($container->privates['.service_locator.Ttk9YRP'])) {
            return $container->privates['.service_locator.Ttk9YRP'];
        }

        return $container->privates['.service_locator.Ttk9YRP'] = $instance;
    }
}
