<?php

namespace ContainerIZF4qrH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBddControllershowArticleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RGWK.nN.App\Controller\BddController::show_article()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RGWK.nN.App\\Controller\\BddController::show_article()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'articleRepository' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
            'article' => ['privates', '.errored..service_locator.RGWK.nN.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.RGWK.nN": it needs an instance of "App\\Entity\\Article" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'articleRepository' => 'App\\Repository\\ArticleRepository',
            'article' => 'App\\Entity\\Article',
        ]))->withContext('App\\Controller\\BddController::show_article()', $container);
    }
}
