<?php

namespace ContainerIZF4qrH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBddControllershowRestaurantService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JOUdUxO.App\Controller\BddController::show_restaurant()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JOUdUxO.App\\Controller\\BddController::show_restaurant()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'restaurantRepository' => ['privates', 'App\\Repository\\RestaurantRepository', 'getRestaurantRepositoryService', true],
            'restaurant' => ['privates', '.errored..service_locator.JOUdUxO.App\\Entity\\Restaurant', NULL, 'Cannot autowire service ".service_locator.JOUdUxO": it needs an instance of "App\\Entity\\Restaurant" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'restaurantRepository' => 'App\\Repository\\RestaurantRepository',
            'restaurant' => 'App\\Entity\\Restaurant',
        ]))->withContext('App\\Controller\\BddController::show_restaurant()', $container);
    }
}
