<?php

namespace ContainerTGjqde1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SK_6_DService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.S_K.6.d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.S_K.6.d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'registerRepository' => ['privates', '.errored.Ty_odqF', NULL, 'Cannot determine controller argument for "App\\Controller\\BddController::register()": the $registerRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\RegisterRepository". Did you forget to add a use statement?'],
        ], [
            'registerRepository' => '?',
        ]);
    }
}
