<?php

namespace ContainerTGjqde1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ur7ISService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ur7_I_s' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\BddController::index' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\BddController::index()', 'getBddControllerindexService', true],
            'App\\Controller\\BddController::show_article' => ['privates', '.service_locator.RGWK.nN.App\\Controller\\BddController::show_article()', 'getBddControllershowArticleService', true],
            'App\\Controller\\BddController::modifier_article' => ['privates', '.service_locator.V05Esnz.App\\Controller\\BddController::modifier_article()', 'getBddControllermodifierArticleService', true],
            'App\\Controller\\BddController::supprimer_article' => ['privates', '.service_locator.V05Esnz.App\\Controller\\BddController::supprimer_article()', 'getBddControllersupprimerArticleService', true],
            'App\\Controller\\BddController::create_restaurant' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\BddController::create_restaurant()', 'getBddControllercreateRestaurantService', true],
            'App\\Controller\\BddController::modifier_restaurant' => ['privates', '.service_locator.vdrtoh..App\\Controller\\BddController::modifier_restaurant()', 'getBddControllermodifierRestaurantService', true],
            'App\\Controller\\BddController::supprimer_restaurant' => ['privates', '.service_locator.vdrtoh..App\\Controller\\BddController::supprimer_restaurant()', 'getBddControllersupprimerRestaurantService', true],
            'App\\Controller\\BddController::create_commentaire' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\BddController::create_commentaire()', 'getBddControllercreateCommentaireService', true],
            'App\\Controller\\BddController::register' => ['privates', '.service_locator.S_K.6.d', 'get_ServiceLocator_SK_6_DService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.3FWkHlB.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RestaurantController::list' => ['privates', '.service_locator.SerGm_R.App\\Controller\\RestaurantController::list()', 'getRestaurantControllerlistService', true],
            'App\\Controller\\RestaurantController::show' => ['privates', '.service_locator.X__.8es.App\\Controller\\RestaurantController::show()', 'getRestaurantControllershowService', true],
            'App\\Controller\\RestaurantController::add' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\RestaurantController::add()', 'getRestaurantControlleraddService', true],
            'App\\Controller\\RestaurantController::edit' => ['privates', '.service_locator.01RXl9S.App\\Controller\\RestaurantController::edit()', 'getRestaurantControllereditService', true],
            'App\\Controller\\RestaurantController::delete' => ['privates', '.service_locator.01RXl9S.App\\Controller\\RestaurantController::delete()', 'getRestaurantControllerdeleteService', true],
            'App\\Controller\\RestaurantController::addComment' => ['privates', '.service_locator.HHmmroV.App\\Controller\\RestaurantController::addComment()', 'getRestaurantControlleraddCommentService', true],
            'App\\Controller\\RestaurantController::deleteComment' => ['privates', '.service_locator.ngkPSs6.App\\Controller\\RestaurantController::deleteComment()', 'getRestaurantControllerdeleteCommentService', true],
            'App\\Controller\\RestaurantController::restaurantsByCity' => ['privates', '.service_locator.MAK4Uph.App\\Controller\\RestaurantController::restaurantsByCity()', 'getRestaurantControllerrestaurantsByCityService', true],
            'App\\Controller\\RestaurantController::addCity' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\RestaurantController::addCity()', 'getRestaurantControlleraddCityService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\BddController:index' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\BddController::index()', 'getBddControllerindexService', true],
            'App\\Controller\\BddController:show_article' => ['privates', '.service_locator.RGWK.nN.App\\Controller\\BddController::show_article()', 'getBddControllershowArticleService', true],
            'App\\Controller\\BddController:modifier_article' => ['privates', '.service_locator.V05Esnz.App\\Controller\\BddController::modifier_article()', 'getBddControllermodifierArticleService', true],
            'App\\Controller\\BddController:supprimer_article' => ['privates', '.service_locator.V05Esnz.App\\Controller\\BddController::supprimer_article()', 'getBddControllersupprimerArticleService', true],
            'App\\Controller\\BddController:create_restaurant' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\BddController::create_restaurant()', 'getBddControllercreateRestaurantService', true],
            'App\\Controller\\BddController:modifier_restaurant' => ['privates', '.service_locator.vdrtoh..App\\Controller\\BddController::modifier_restaurant()', 'getBddControllermodifierRestaurantService', true],
            'App\\Controller\\BddController:supprimer_restaurant' => ['privates', '.service_locator.vdrtoh..App\\Controller\\BddController::supprimer_restaurant()', 'getBddControllersupprimerRestaurantService', true],
            'App\\Controller\\BddController:create_commentaire' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\BddController::create_commentaire()', 'getBddControllercreateCommentaireService', true],
            'App\\Controller\\BddController:register' => ['privates', '.service_locator.S_K.6.d', 'get_ServiceLocator_SK_6_DService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.3FWkHlB.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RestaurantController:list' => ['privates', '.service_locator.SerGm_R.App\\Controller\\RestaurantController::list()', 'getRestaurantControllerlistService', true],
            'App\\Controller\\RestaurantController:show' => ['privates', '.service_locator.X__.8es.App\\Controller\\RestaurantController::show()', 'getRestaurantControllershowService', true],
            'App\\Controller\\RestaurantController:add' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\RestaurantController::add()', 'getRestaurantControlleraddService', true],
            'App\\Controller\\RestaurantController:edit' => ['privates', '.service_locator.01RXl9S.App\\Controller\\RestaurantController::edit()', 'getRestaurantControllereditService', true],
            'App\\Controller\\RestaurantController:delete' => ['privates', '.service_locator.01RXl9S.App\\Controller\\RestaurantController::delete()', 'getRestaurantControllerdeleteService', true],
            'App\\Controller\\RestaurantController:addComment' => ['privates', '.service_locator.HHmmroV.App\\Controller\\RestaurantController::addComment()', 'getRestaurantControlleraddCommentService', true],
            'App\\Controller\\RestaurantController:deleteComment' => ['privates', '.service_locator.ngkPSs6.App\\Controller\\RestaurantController::deleteComment()', 'getRestaurantControllerdeleteCommentService', true],
            'App\\Controller\\RestaurantController:restaurantsByCity' => ['privates', '.service_locator.MAK4Uph.App\\Controller\\RestaurantController::restaurantsByCity()', 'getRestaurantControllerrestaurantsByCityService', true],
            'App\\Controller\\RestaurantController:addCity' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\RestaurantController::addCity()', 'getRestaurantControlleraddCityService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\BddController::index' => '?',
            'App\\Controller\\BddController::show_article' => '?',
            'App\\Controller\\BddController::modifier_article' => '?',
            'App\\Controller\\BddController::supprimer_article' => '?',
            'App\\Controller\\BddController::create_restaurant' => '?',
            'App\\Controller\\BddController::modifier_restaurant' => '?',
            'App\\Controller\\BddController::supprimer_restaurant' => '?',
            'App\\Controller\\BddController::create_commentaire' => '?',
            'App\\Controller\\BddController::register' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RestaurantController::list' => '?',
            'App\\Controller\\RestaurantController::show' => '?',
            'App\\Controller\\RestaurantController::add' => '?',
            'App\\Controller\\RestaurantController::edit' => '?',
            'App\\Controller\\RestaurantController::delete' => '?',
            'App\\Controller\\RestaurantController::addComment' => '?',
            'App\\Controller\\RestaurantController::deleteComment' => '?',
            'App\\Controller\\RestaurantController::restaurantsByCity' => '?',
            'App\\Controller\\RestaurantController::addCity' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\BddController:index' => '?',
            'App\\Controller\\BddController:show_article' => '?',
            'App\\Controller\\BddController:modifier_article' => '?',
            'App\\Controller\\BddController:supprimer_article' => '?',
            'App\\Controller\\BddController:create_restaurant' => '?',
            'App\\Controller\\BddController:modifier_restaurant' => '?',
            'App\\Controller\\BddController:supprimer_restaurant' => '?',
            'App\\Controller\\BddController:create_commentaire' => '?',
            'App\\Controller\\BddController:register' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RestaurantController:list' => '?',
            'App\\Controller\\RestaurantController:show' => '?',
            'App\\Controller\\RestaurantController:add' => '?',
            'App\\Controller\\RestaurantController:edit' => '?',
            'App\\Controller\\RestaurantController:delete' => '?',
            'App\\Controller\\RestaurantController:addComment' => '?',
            'App\\Controller\\RestaurantController:deleteComment' => '?',
            'App\\Controller\\RestaurantController:restaurantsByCity' => '?',
            'App\\Controller\\RestaurantController:addCity' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);

        if (isset($container->privates['.service_locator.Ur7_I_s'])) {
            return $container->privates['.service_locator.Ur7_I_s'];
        }

        return $container->privates['.service_locator.Ur7_I_s'] = $instance;
    }
}
