<?php

namespace ContainerTGjqde1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Vdrtoh_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vdrtoh.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'restaurant' => ['privates', '.errored..service_locator.vdrtoh..App\\Entity\\Restaurant', NULL, 'Cannot autowire service ".service_locator.vdrtoh.": it needs an instance of "App\\Entity\\Restaurant" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'restaurant' => 'App\\Entity\\Restaurant',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.vdrtoh.'])) {
            return $container->privates['.service_locator.vdrtoh.'];
        }

        return $container->privates['.service_locator.vdrtoh.'] = $instance;
    }
}
