<?php

namespace ContainerTGjqde1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_TyOdqFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.Ty_odqF' shared service.
     *
     * @return \App\Controller\RegisterRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\BddController::register()": the $registerRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\RegisterRepository". Did you forget to add a use statement?');
    }
}
