<?php

namespace ContainerTGjqde1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRestaurantControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.01RXl9S.App\Controller\RestaurantController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.01RXl9S'] ?? $container->load('get_ServiceLocator_01RXl9SService'));

        if (isset($container->privates['.service_locator.01RXl9S.App\\Controller\\RestaurantController::edit()'])) {
            return $container->privates['.service_locator.01RXl9S.App\\Controller\\RestaurantController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\RestaurantController::edit()', $container);

        if (isset($container->privates['.service_locator.01RXl9S.App\\Controller\\RestaurantController::edit()'])) {
            return $container->privates['.service_locator.01RXl9S.App\\Controller\\RestaurantController::edit()'];
        }

        return $container->privates['.service_locator.01RXl9S.App\\Controller\\RestaurantController::edit()'] = $instance;
    }
}
