<?php

namespace ContainerTGjqde1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRestaurantService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.01RXl9S.App\Entity\Restaurant' shared service.
     *
     * @return \App\Entity\Restaurant
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.01RXl9S": it needs an instance of "App\\Entity\\Restaurant" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
