<?php

namespace ContainerDol7ueB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBddControllerlistRestaurantsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UtX_ugi.App\Controller\BddController::list_restaurants()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UtX_ugi.App\\Controller\\BddController::list_restaurants()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'restaurantRepository' => ['privates', 'App\\Repository\\RestaurantRepository', 'getRestaurantRepositoryService', true],
        ], [
            'restaurantRepository' => 'App\\Repository\\RestaurantRepository',
        ]))->withContext('App\\Controller\\BddController::list_restaurants()', $container);
    }
}
