<?php

namespace ContainerKFZKtrk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_Gg_Ej15Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.Gg.Ej15' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/src/MessageHandler/NouveauCommentaireHandler.php';

        return $container->privates['.messenger.handler_descriptor.Gg.Ej15'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\MessageHandler\NouveauCommentaireHandler(($container->privates['App\\Repository\\CommentaireRepository'] ?? $container->load('getCommentaireRepositoryService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'))), []);
    }
}
