<?php

namespace ContainerKFZKtrk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBddControllersupprimerArticleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.V05Esnz.App\Controller\BddController::supprimer_article()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.V05Esnz'] ?? $container->load('get_ServiceLocator_V05EsnzService'));

        if (isset($container->privates['.service_locator.V05Esnz.App\\Controller\\BddController::supprimer_article()'])) {
            return $container->privates['.service_locator.V05Esnz.App\\Controller\\BddController::supprimer_article()'];
        }

        $instance = $a->withContext('App\\Controller\\BddController::supprimer_article()', $container);

        if (isset($container->privates['.service_locator.V05Esnz.App\\Controller\\BddController::supprimer_article()'])) {
            return $container->privates['.service_locator.V05Esnz.App\\Controller\\BddController::supprimer_article()'];
        }

        return $container->privates['.service_locator.V05Esnz.App\\Controller\\BddController::supprimer_article()'] = $instance;
    }
}
