<?php

namespace ContainerKFZKtrk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRestaurantControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.X__.8es.App\Controller\RestaurantController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X__.8es.App\\Controller\\RestaurantController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'restaurant' => ['privates', '.errored..service_locator.X__.8es.App\\Entity\\Restaurant', NULL, 'Cannot autowire service ".service_locator.X__.8es": it needs an instance of "App\\Entity\\Restaurant" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'restaurant' => 'App\\Entity\\Restaurant',
        ]))->withContext('App\\Controller\\RestaurantController::show()', $container);
    }
}
