<?php

namespace ContainerKFZKtrk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRestaurantControllerdeleteCommentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ngkPSs6.App\Controller\RestaurantController::deleteComment()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commentaire' => ['privates', '.errored..service_locator.ngkPSs6.App\\Entity\\Commentaire', NULL, 'Cannot autowire service ".service_locator.ngkPSs6": it needs an instance of "App\\Entity\\Commentaire" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'commentaire' => 'App\\Entity\\Commentaire',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\RestaurantController::deleteComment()', $container);

        if (isset($container->privates['.service_locator.ngkPSs6.App\\Controller\\RestaurantController::deleteComment()'])) {
            return $container->privates['.service_locator.ngkPSs6.App\\Controller\\RestaurantController::deleteComment()'];
        }

        return $container->privates['.service_locator.ngkPSs6.App\\Controller\\RestaurantController::deleteComment()'] = $instance;
    }
}
