<?php

namespace ContainerKFZKtrk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRestaurantControllerlistService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SerGm_R.App\Controller\RestaurantController::list()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SerGm_R.App\\Controller\\RestaurantController::list()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'restaurantRepository' => ['privates', 'App\\Repository\\RestaurantRepository', 'getRestaurantRepositoryService', true],
            'villeRepository' => ['privates', 'App\\Repository\\VilleRepository', 'getVilleRepositoryService', true],
        ], [
            'restaurantRepository' => 'App\\Repository\\RestaurantRepository',
            'villeRepository' => 'App\\Repository\\VilleRepository',
        ]))->withContext('App\\Controller\\RestaurantController::list()', $container);
    }
}
