<?php

namespace ContainerKFZKtrk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRestaurantControllerrestaurantsByCityService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MAK4Uph.App\Controller\RestaurantController::restaurantsByCity()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MAK4Uph.App\\Controller\\RestaurantController::restaurantsByCity()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ville' => ['privates', '.errored..service_locator.MAK4Uph.App\\Entity\\Ville', NULL, 'Cannot autowire service ".service_locator.MAK4Uph": it needs an instance of "App\\Entity\\Ville" but this type has been excluded because it\'s a Doctrine entity.'],
            'restaurantRepository' => ['privates', 'App\\Repository\\RestaurantRepository', 'getRestaurantRepositoryService', true],
            'villeRepository' => ['privates', 'App\\Repository\\VilleRepository', 'getVilleRepositoryService', true],
        ], [
            'ville' => 'App\\Entity\\Ville',
            'restaurantRepository' => 'App\\Repository\\RestaurantRepository',
            'villeRepository' => 'App\\Repository\\VilleRepository',
        ]))->withContext('App\\Controller\\RestaurantController::restaurantsByCity()', $container);
    }
}
