<?php

namespace ContainerKFZKtrk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRestaurantControlleraddCommentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HHmmroV.App\Controller\RestaurantController::addComment()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'restaurant' => ['privates', '.errored..service_locator.HHmmroV.App\\Entity\\Restaurant', NULL, 'Cannot autowire service ".service_locator.HHmmroV": it needs an instance of "App\\Entity\\Restaurant" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'bus' => ['services', 'messenger.default_bus', 'getMessenger_DefaultBusService', false],
        ], [
            'restaurant' => 'App\\Entity\\Restaurant',
            'entityManager' => '?',
            'bus' => '?',
        ]))->withContext('App\\Controller\\RestaurantController::addComment()', $container);

        if (isset($container->privates['.service_locator.HHmmroV.App\\Controller\\RestaurantController::addComment()'])) {
            return $container->privates['.service_locator.HHmmroV.App\\Controller\\RestaurantController::addComment()'];
        }

        return $container->privates['.service_locator.HHmmroV.App\\Controller\\RestaurantController::addComment()'] = $instance;
    }
}
