<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKFZKtrk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKFZKtrk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKFZKtrk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKFZKtrk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKFZKtrk\App_KernelDevDebugContainer([
    'container.build_hash' => 'KFZKtrk',
    'container.build_id' => '2d431ac6',
    'container.build_time' => 1791641189,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKFZKtrk');
