<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDol7ueB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDol7ueB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDol7ueB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDol7ueB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDol7ueB\App_KernelDevDebugContainer([
    'container.build_hash' => 'Dol7ueB',
    'container.build_id' => '9c370591',
    'container.build_time' => 1791446851,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDol7ueB');
